---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "odoo2-service"
  namespace: "default"
  labels:
    io.kompose.service: "odoo2"
spec:
  ports:
  - name: "8069-to-8069-tcp"
    protocol: "TCP"
    port: 8069
    targetPort: 8069
  - name: "8072-to-8072-tcp"
    protocol: "TCP"
    port: 8072
    targetPort: 8072
  selector:
    io.kompose.service: "odoo2"
  # type: "ClusterIP" 
  type: LoadBalancer 
  # loadBalancerIP: 108.137.120.188
