apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-07-19T09:55:32Z"
  generation: 2
  labels:
    app: nginx
  name: nginx
  namespace: default
  # resourceVersion: "693081"
  # uid: 5b2fdcfc-001e-49fb-9f29-0693423de96a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: vol-nginx-confd
        - mountPath: /etc/ssl/certs
          name: vol-nginx-certs 
        ports:
        - containerPort: 80
          name: http-web-svc
        - containerPort: 443
          name: https-web-svc
        - containerPort: 8072
          name: lp-web-svc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-nginx-confd
          persistentVolumeClaim:
            claimName: nfs-pvc-confd
        - name: vol-nginx-certs 
          persistentVolumeClaim:
            claimName: nfs-pvc-certs
# status:
#   availableReplicas: 1
#   conditions:
#   - lastTransitionTime: "2022-07-19T09:55:40Z"
#     lastUpdateTime: "2022-07-19T09:55:40Z"
#     message: Deployment has minimum availability.
#     reason: MinimumReplicasAvailable
#     status: "True"
#     type: Available
#   - lastTransitionTime: "2022-07-19T09:55:32Z"
#     lastUpdateTime: "2022-07-19T09:55:40Z"
#     message: ReplicaSet "nginx-b77c8bcf7" has successfully progressed.
#     reason: NewReplicaSetAvailable
#     status: "True"
#     type: Progressing
#   observedGeneration: 2
#   readyReplicas: 1
#   replicas: 1
#   updatedReplicas: 1