version: '3.3'
services:
  web:
    image: 'nginx:latest'
    container_name: webserver
    networks:
      - docker-net
    ports:
      - "80:80"
    volumes:
      - vol_nginx:/usr/share/nginx/html
  
  healthcheck:
    test: curl --fail http://localhost || exit 1
    interval: 60s
    retries: 5
    start_period: 20s
    timeout: 10s

networks:
    docker-net:
        external:
            name: docker-net

volumes:
    vol_nginx:
        external: true